stages:
  - build
  - push
  - deploy

variables:  
  CI_REGISTRY: "registry.gitlab.com"
  IMAGE_TAG: $CI_COMMIT_SHORT_SHA
  


before_script:
  # Устанавливаем необходимые пакеты в Alpine
  - apk add --no-cache curl tar gzip
  # Устанавливаем Helm
  - export HELM_VERSION=v3.8.0
  - curl -fsSL https://get.helm.sh/helm-${HELM_VERSION}-linux-amd64.tar.gz -o helm.tar.gz
  - tar -zxvf helm.tar.gz
  - mv linux-amd64/helm /usr/local/bin/helm
  - helm version
  # Устанавливаем kubectl
  - curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
  - chmod +x kubectl
  - mv kubectl /usr/local/bin/
  - kubectl version --client
  # Настраиваем kubeconfig для доступа к Kubernetes
  - mkdir -p ~/.kube
  - echo "$KUBERNETES_CONFIG" | base64 -d > ~/.kube/config


build-job:
  stage: build
  script:
    # Собираем Docker образ из Dockerfile
    - docker build -t $DOCKER_IMAGE:$IMAGE_TAG .

push-job:
  stage: push
  script:
    # Входим в GitLab Container Registry
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY

    # Пушим образ в реестр GitLab
    - docker push $DOCKER_IMAGE:$IMAGE_TAG

deploy:
  stage: deploy
  script:
    - helm repo add --username $CI_REGISTRY_USER --password $ACCESS_TOKEN flaskapp https://gitlab.com/api/v4/projects/$PROJECT_ID/packages/helm/stable
    - helm repo update
    - helm pull flaskapp/backend-chart --version 0.1.0
    - helm upgrade --install flaskapp-$IMAGE_TAG backend-chart-0.1.0.tgz --set backend.Image.repository=$DOCKER_IMAGE:$IMAGE_TAG
