stages:
  - build
  - push

variables:

  CI_REGISTRY: "registry.gitlab.com"


build:
  stage: build
  script:
    # Собираем Docker образ из Dockerfile
    - docker build -t $DOCKER_IMAGE .

push:
  stage: push
  script:
    # Входим в GitLab Container Registry
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY

    # Пушим образ в реестр GitLab
    - docker push $DOCKER_IMAGE