replicaCount: 2  # Количество реплик

AppLabels: backend

backend:
  ContainersName: backend
  service:
    type: ClusterIP
    port: 5050
    targetPort: 5050
    #nodePort: 30000
  Image:
    repository: kostomarush/flaskback:v1.0
  


postgres:
  ContainersName: postgres
  service:
    type: ClusterIP
    port: 5432
    targetPort: 5432
    volume: 
      name: postgres-data
      mountPath: /var/lib/postgresql/data
      hostPath: /mnt/data
  Image:
    repository: postgres:16


env:
  DB_HOST: "postgres"
  DB_NAME: "test_db"
  DB_USER: "postgres"
  DB_PORT: "5432"

secrets:
  DB_PASSWORD: "P@ssw0rd"

resources:
  limits:
    cpu: 500m
    memory: 128Mi

ingress:
  ingressClassName: nginx
  rules:
    host: flaskapp.local
    paths:
      path: /tables
      pathType: Prefix
      backend:
        service:
          name: backend
          port: 5050
  
