apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-backend-config
data:
  DB_HOST:  "{{ .Values.env.DB_HOST }}"
  DB_NAME:  "{{ .Values.env.DB_NAME }}"
  DB_USER:  "{{ .Values.env.DB_USER }}"
  DB_PORT:  "{{ .Values.env.DB_PORT }}"