apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-backend
spec:
  replicas: {{ .Values.replicaCount }} #Количество подов в кластере
  selector:
    matchLabels:
      app: {{ .Values.AppLabels }} #указывает, какие поды должен управлять Deployment.
  template:
    metadata:
      labels:
        app: {{ .Values.AppLabels }} #именнование подов
    spec:
      containers:
      - name: {{ .Values.backend.ContainersName }}
        image: {{ .Values.backend.Image.repository }} #Образ контейнеров
        resources:
          limits:
            memory: {{ .Values.resources.limits.memory }}
            cpu: {{ .Values.resources.limits.cpu }}
        ports:
        - containerPort: {{ .Values.backend.service.targetPort }} #прокидывает порт контейнера внутри кластера
        envFrom:
        - configMapRef:
            name: {{ .Release.Name }}-backend-config
        - secretRef:
            name: {{ .Release.Name }}-backend-secret
      - name: {{ .Values.postgres.ContainersName }}
        image: {{ .Values.postgres.Image.repository }}
        resources:
          limits:
            memory: {{ .Values.resources.limits.memory }}
            cpu: {{ .Values.resources.limits.cpu }}
        envFrom:
        - configMapRef:
            name: {{ .Release.Name }}-backend-config
        - secretRef:
            name: {{ .Release.Name }}-backend-secret
        ports:
        - containerPort: {{ .Values.postgres.service.targetPort }}
        volumeMounts:
        - name: {{ .Values.postgres.service.volume.name }}
          mountPath: {{ .Values.postgres.service.volume.mountPath }}
      volumes:
        - name: {{ .Values.postgres.service.volume.name }}
          hostPath:
            path: {{ .Values.postgres.service.volume.hostPath }}



