apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backend.ContainersName }}
spec:
  selector:
    app: {{ .Values.AppLabels }}
  ports:
  - port: {{ .Values.backend.service.port }}
    nodePort: {{ .Values.backend.service.nodePort }}
    targetPort: {{ .Values.backend.service.targetPort }}
  type: {{ .Values.backend.service.type }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgres.ContainersName }}
spec:
  selector:
    app: {{ .Values.AppLabels }}
  ports:
  - port: {{ .Values.postgres.service.port }}
    targetPort: {{ .Values.postgres.service.targetPort }}
  type: {{ .Values.postgres.service.type }}